---
- name: Install parted dependency
  yum:
    name: parted
    state: present

- name: create docker partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 100MB

- name: Create directory /var/lib/docker/ if does not exist
  file:
    path: /var/lib/docker/
    state: directory
    mode: '0755'

- name: format the xfs filesystem
  filesystem:
    fstype: ext2
    dev: /dev/sdb1

- name: mount the lv on /var/lib/docker/
  mount:
    path: /var/lib/docker/
    src: /dev/sdb1
    fstype: ext2
    state: mounted

# https://www.redhat.com/sysadmin/automating-logical-volume-manager