---
- name: Install parted dependency
  ansible.builtin.yum:
    name: parted
    state: present

- name: Create docker partition
  parted:
    device: "{{ docker_block_device }}"
    number: 1
    flags: [ lvm ]
    state: present
    part_end: "{{ docker_storage_size }}"

- name: Create directory /var/lib/docker/ if does not exist
  ansible.builtin.file:
    path: /var/lib/docker/
    state: directory
    mode: '0755'

- name: Format the filesystem
  filesystem:
    fstype: ext2
    dev: "{{ docker_block_device }}1"

- name: Mount the partition on /var/lib/docker/
  mount:
    path: /var/lib/docker/
    src: "{{ docker_block_device }}1"
    fstype: ext2
    state: mounted

# https://www.redhat.com/sysadmin/automating-logical-volume-manager