---
# handlers file for ansible_docker
- name: reload systemd configuration
  ansible.builtin.systemd:
    state: restarted
    name: docke
- name: restart docker engine
  ansible.builtin.service: name=docker state=restarted