---
# handlers file for ansible_docker
- name: reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes
- name: restart docker engine
  ansible.builtin.service: name=docker state=restarted