---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: centos/7
    privileged: true
    memory: 4096
    cpus: 2
    interfaces:
      # `network_name` is the required identifier, other keys map to arguments.
      - network_name: private_network
        ip: 192.168.56.10
#    config_options:
#      ssh.keep_alive: yes
#      ssh.remote_user: "'vagrant'"
    # configure second partition
    provider_raw_config_args:
    - "customize
       ['createhd',
        '--filename', 'extradisk_centos_7.vdi',
        '--size', 1024]"
    - "customize
       ['storageattach', :id,
        '--storagectl', 'IDE',
        '--port', 1,
        '--device', 1,
        '--type', 'hdd',
        '--medium', 'extradisk_centos_7.vdi']"
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  name: default
  test_sequence:
  - destroy
  - create
  - converge
  # - idempotence
  - lint
  - verify
verifier:
  name: testinfra
